version: '3'
services:
      web:
        image: angular-app
        build: ./angular-app
        ports:
          - "80:80"
        depends_on:
          - node-server
      node-server:
        image: node-server
        build: ./node-api
        ports:
          - "3000:3000"
        depends_on:
          - mongo
      mongo:
        image: mongo
        ports:
          - "27017:27017"